### ISSUE TITLE
text_box: returns an Array on truncate and inline_format=true

### ISSUE THREAD

**Issue by andymeneely** [prawnpdf/prawn#1038]
I think this was what #917 was talking about - I just ran into it myself. Here's an example: 

```ruby
require 'prawn'

text = "<b>test</b>!! " * 50
excess = ''

Prawn::Document.generate("text_box_overflow_inline_format.pdf"
  ) do
  bounding_box([0,770], :width => 160, height: 252) do
    transparent(0.5) { stroke_bounds }
    excess = text_box text,
                      width: 160,
                      height: 232,
                      overflow: :truncate,
                      indent: 10,
                      inline_format: true # this code works if you set this to false
  end
  bounding_box([180,770], :width => 160, height: 252) do
    transparent(0.5) { stroke_bounds }
    text_box excess,
             width: 160,
             height: 232,
             overflow: :truncate,
             indent: 10,
             inline_format: true
  end
end
```

Here's the output:
```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/text/formatted/parser.rb:34:in `format': undefined method `gsub' for []:Array (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/text/box.rb:111:in `text_box'
        from prawn_bug.rb:20:in `block (2 levels) in <main>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/document/bounding_box.rb:196:in `init_bounding_box'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/document/bounding_box.rb:157:in `bounding_box'
        from prawn_bug.rb:18:in `block in <main>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/document.rb:236:in `instance_eval'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/document.rb:236:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/document.rb:142:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib/prawn/document.rb:142:in `generate'
```

Prawn 2.2.2, Ruby 2.4.1p111 on Windows 10

**Comment by andymeneely** [comment]
Ok so the behavior is still unexpected but I was able to work around it. The Array that gets returned is the same kind of array that `formatted_text_box` expects. So the *second* time you need text, just use formatted_text_box. 

This makes my code kind of messy because I have a string of text boxes throughout my document and I have to handle the first case separately. But at least I can continue to work with it.
