### ISSUE TITLE
"Prawn manual contains no unexpected changes" test fails on master

### ISSUE THREAD

**Issue by Apteryks** [prawnpdf/prawn#1163]
It fails reproducibly:

```
bundle exec rspec
`/homeless-shelter` is not a directory.
Bundler will use `/tmp/guix-build-ruby-prawn-2.2.2.drv-0/bundler/home/myuser' as your home directory temporarily.
Prawn specs: Running on Ruby Version: 2.6.5
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F

Failures:

  1) Prawn manual contains no unexpected changes
     Failure/Error: expect(hash).to eq MANUAL_HASH
     
       expected: "ea401febcaf2d71a374bc7f25753568ec07dde3479597091498acf4c42c7fd6f9a94f4a42e5b366b947cc0c2623a3a6c6990cd7a9bbffa63babd1c61290c1ad6"
            got: "85d2ded146d1e6659e9db389a071896d6e57d7cc4210c6b7fc75fc4afe2b56978a86baca785acd717964619dc234327ef59f5ba6d750dfd626279af0166f6c5e"
     
       (compared using ==)
     # ./spec/prawn_manual_spec.rb:32:in `block (3 levels) in <top (required)>'

Finished in 20.05 seconds (files took 0.5327 seconds to load)
861 examples, 1 failure

Failed examples:

rspec ./spec/prawn_manual_spec.rb:24 # Prawn manual contains no unexpected changes
```

**Comment by pointlessone** [comment]
Could you please attach generated manual for inspection?

Please use the following command to generate it:
```
CI=1 bundle exec rake manual
```

**Comment by Apteryks** [comment]
Hello, thanks for the prompt reply. Here is the generated manual:

[manual.pdf](https://github.com/prawnpdf/prawn/files/4926191/manual.pdf)

**Comment by petergoldstein** [comment]
@pointlessone I think this can be closed.  We're not seeing any such failure in CI at this time.

**Comment by Apteryks** [comment]
For what it's worth, I can still reproduce this as of ruby-prawn 2.4.0 on GNU Guix:

```
starting phase `check'
Prawn specs: Running on Ruby Version: 2.7.4
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F

Failures:

  1) Prawn manual contains no unexpected changes
     Failure/Error: expect(hash).to eq MANUAL_HASH

       expected: "79248d58f9d89e44081da875fa15ad9a70cc07e9eaa4e8b706001044a3570e3fbc4b5ba3e1150868d88add3a43972265219d4d11c60cbbc1bebf50e7d26cdb60"
            got: "9dc5ef5ab500419756784c3f79f309c001a63a604d53e072972c01115f3779f5e6df56f441b25661494df650d184ced33ac02f0ed135b49829549d7676644fd8"

       (compared using ==)
     # ./spec/prawn_manual_spec.rb:32:in `block (3 levels) in <top (required)>'

Finished in 8.07 seconds (files took 0.21625 seconds to load)
865 examples, 1 failure

Failed examples:

rspec ./spec/prawn_manual_spec.rb:24 # Prawn manual contains no unexpected changes

error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "rspec" arguments: () exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 8.4 seconds
command "rspec" failed with status 1
```
The following dependencies were used:
```
dependencies: ruby-matrix@0.4.2 ruby-pdf-core@0.9.0 ruby-pdf-inspector@1.3.0-1.00ee4c9
+ ruby-prawn-dev@0.3.0 ruby-prawn-manual-builder@0.3.1 ruby-ttfunk@1.7.
```
