### ISSUE TITLE
The gem breaks runtime

### ISSUE THREAD

**Issue by gerard-morera** [prawnpdf/prawn#1274]
Any idea how to fix it?

```
C:\Users\ACER\api-core>rails c
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- matrix (LoadError)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/transformation_stack.rb:10:in `<main>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn.rb:67:in `require_relative'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn.rb:67:in `<main>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from C:/Ruby31-x64/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from C:/Ruby31-x64/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
        from C:/Ruby31-x64/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
        from C:/Ruby31-x64/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
        from C:/Ruby31-x64/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
        from C:/Ruby31-x64/lib/ruby/3.1.0/bundler.rb:176:in `require'
```

**Comment by johnnyshields** [comment]
Add `gem "matrix"` to your gemfile.

@pointlessone pinging on this, users would really appreciate a release to fix this long-standing issue.

**Comment by gerard-morera** [comment]
Yes, thanks I found it now in stackoverflow:

[CONTEXT](https://stackoverflow.com/a/72031582)
