### ISSUE TITLE
2 test failures after updating rspec to 3.12

### ISSUE THREAD

**Issue by Apteryks** [prawnpdf/prawn#1299]
Hi,

After updating rspec to 3.12, I see the following test failures:
```
Failures:

  1) Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is not set adds content 'B'
     Failure/Error: prawn.send(call, *arguments, **kwarguments)
       #<InstanceDouble(Prawn::Document) (anonymous)> received unexpected message :rectangle with ([0.0, 100.0], 10.0, 10.0)
     # ./lib/prawn/svg/interface.rb:124:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:116:in `block (2 levels) in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:215:in `rewrite_call_arguments'
     # ./lib/prawn/svg/interface.rb:115:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:108:in `block in proc_creator'
     # ./lib/prawn/svg/interface.rb:51:in `block (3 levels) in draw'
     # ./spec/prawn/svg/interface_spec.rb:38:in `block (5 levels) in <top (required)>'
     # ./lib/prawn/svg/interface.rb:44:in `block (2 levels) in draw'
     # ./lib/prawn/svg/interface.rb:43:in `block in draw'
     # ./lib/prawn/svg/interface.rb:42:in `draw'
     # ./spec/prawn/svg/interface_spec.rb:49:in `block (6 levels) in <top (required)>'

  2) Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is evenodd adds content 'B*'
     Failure/Error: prawn.send(call, *arguments, **kwarguments)
       #<InstanceDouble(Prawn::Document) (anonymous)> received unexpected message :rectangle with ([0.0, 100.0], 10.0, 10.0)
     # ./lib/prawn/svg/interface.rb:124:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:116:in `block (2 levels) in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:215:in `rewrite_call_arguments'
     # ./lib/prawn/svg/interface.rb:115:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:108:in `block in proc_creator'
     # ./lib/prawn/svg/interface.rb:51:in `block (3 levels) in draw'
     # ./spec/prawn/svg/interface_spec.rb:38:in `block (5 levels) in <top (required)>'
     # ./lib/prawn/svg/interface.rb:44:in `block (2 levels) in draw'
     # ./lib/prawn/svg/interface.rb:43:in `block in draw'
     # ./lib/prawn/svg/interface.rb:42:in `draw'
     # ./spec/prawn/svg/interface_spec.rb:60:in `block (6 levels) in <top (required)>'

Finished in 0.69992 seconds (files took 0.20944 seconds to load)
296 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/prawn/svg/interface_spec.rb:45 # Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is not set adds content 'B'
rspec ./spec/prawn/svg/interface_spec.rb:56 # Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is evenodd adds content 'B*'
```

Thanks!

**Comment by Apteryks** [comment]
Sorry, I misfiled this, it's for prawn-svg.  I'll repopen at the correct place.
