### ISSUE TITLE
undefined local variable or method `array' when rotate on draw_text

### ISSUE THREAD

**Issue by kaluznyo** [prawnpdf/prawn#838]
I get error with prawn 2.0 when I try to get this

```ruby
pdf = Prawn::Document.new
pdf.draw_text 'TEXT', size: 9, at: [30, 0], rotate: 20
```
Log :
```
NameError: undefined local variable or method `array' for #<Prawn::Document:0x007fc2591d54e8>
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/pdf-core-0.5.0/lib/pdf/core/text.rb:241:in `add_text_content'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/prawn-2.0.0/lib/prawn/text.rb:301:in `draw_text!'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/prawn-2.0.0/lib/prawn/text.rb:282:in `block (2 levels) in draw_text'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/prawn-2.0.0/lib/prawn/font.rb:102:in `font_size'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/prawn-2.0.0/lib/prawn/text.rb:282:in `block in draw_text'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/prawn-2.0.0/lib/prawn/font.rb:208:in `save_font'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/prawn-2.0.0/lib/prawn/text.rb:279:in `draw_text'
	from (irb):4
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/olivierkaluzny/.rvm/gems/ruby-2.2.0@project/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
```

**Comment by practicingruby** [comment]
Hi @kaluznyo,

This is a known issue with PDF::Core, see here for details: https://github.com/prawnpdf/pdf-core/pull/15/

Suggested workarounds are to use `:rotate` with any Prawn text method other than the `draw_text` method (i.e. `text`, `text_box`, `formatted_text`, etc.), because it does not rely on the same code. You can also temporarily build pdf-core from the branch listed in the pull request above.

I will try to cut a Prawn 2.0.1 release later this week which fixes this issue. Until then, hope that helps!

**Comment by practicingruby** [comment]
Building prawn from `stable` or `master` should fix this issue now. I'll try to get a new release out within the next few days.

**Comment by practicingruby** [comment]
Prawn 2.0.1 has been released, and it includes this fix!
