### ISSUE TITLE
Error on using inline format with text_box

### ISSUE THREAD

**Issue by davidakachaos** [prawnpdf/prawn#917]
Something strange...
```ruby
options = {:inline_format=>true, :overflow=>:truncate, :height=>83.1496062992126, :width=>42.51968503937008, :at=>[119.05511811023625, 547.0866141732284], :align=>:left, :color=>"000000", :font_size=>7}
txt = 'test tekst'

text_box txt_content, options
```
Above code errors with this:
```
undefined method `encode' for #<Array:0x0055640ef87970>
NoMethodError: undefined method `encoding' for #<Array:0x0055640ef87970>
	from /home/david/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/font/ttf.rb:173:in `rescue in normalize_encoding'
	from /home/david/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/font/ttf.rb:168:in `normalize_encoding'
	from /home/david/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/text/formatted/box.rb:379:in `block in normalize_encoding'
```
If I leave off the option :inline_format => true it works!
```ruby
options = {:overflow=>:truncate, :height=>83.1496062992126, :width=>42.51968503937008, :at=>[119.05511811023625, 360.34960629921267], :align=>:left, :color=>"000000", :font_size=>7}
txt = 'test tekst'

text_box txt_content, options
```
I've read somewhere I need to convert the text into text fragments? Or should the option inline_format 'just work'?

**Comment by iamjohnford** [comment]
Testing that code worked okay on my side as long as you change `txt_content` to `txt`. Is txt_content set somewhere else in your code and causing the issue? You may also want to turn on `Prawn.debug = true` to check the parameters you're using. Some of them are not valid.

```
require 'prawn'
Prawn.debug = true

Prawn::Document.generate("test.pdf") do
  options = {
    :inline_format => true,
    :overflow      => :truncate,
    :height        => 83.1496062992126,
    :width         => 42.51968503937008,
    :at            => [119.05511811023625, 547.0866141732284],
    :align         => :left
  }
  txt = 'test tekst'
  text_box txt, options
end
```

**Comment by packetmonkey** [comment]
If you can please include a fully runnable script with what version of prawn you see it on, we can see what is going on and at lest hopefully provide a more useful error message for people who run into the same issue.

We can re-open once we have that, thanks!
